version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./client
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8000

  api: 
    depends_on: 
      - db
    build: ./api
    ports: 
      - 8000:8000
    environment: 
      DB_URL: mongodb://db/qr

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - qr:/data/db

volumes:
  qr: